### ISSUE TITLE
Methode ontwikkelen om alle bedrijven op branche te selecteren

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Bedrijvenatlas-RH#18]

**Comment by KevinvdBosch** [comment]
SBI codes:
    A: Landbouw, bosbouw, visserij (01..-03..)
    B: Winning van delfstoffen (06..-09..)
    C: Industrie (10..-33..)
    D: Productie en distributie van en handel in elektriciteit, aardgas, stroom en gekoelde lucht (35..)
    E: Winning en distributie van water; afval- en afvalwaterbeheer en sanering (36..-39..)
    F: Bouwnijverheid (41..-43..)
    G: Groot- en detailhandel; reparatie van auto's (45..-47..)
    H: Vervoer en opslag (49..-53..)
    I: Logies-, maaltijd- en drankverstrekking (55..-56..)
    J: Informatie en communicatie (58..-63..)
    K: Financiële instellingen (64..-66..)
    L: Verhuur van en handel in onroerend goed (68..)
    M: Advisering, onderzoek en overige specialistische zakelijke dienstverlening (69..-75..)
    N: Verhuur van roerende goederen en overige zakelijke dienstverlening (77..-82..)
    O: Openbaar bestuur, overheidsdiensten en verplichte sociale verzekeringen (84..)
    P: Onderwijs (85..)
    Q: Gezondheids- en welzijnszorg (86..-88.)
    R: Cultuur, sport en recreatie (90..-93..)
    S: Overige dienstverlening (94..-96..)
    T: Huishoudens als werkgever (97..-98..)
    U: Extraterritoriale organisaties en lichamen (99..)

**Comment by HermanAssink** [comment]
@KevinvdBosch: Hoe hou je deze lijst buiten de programmatuur?

**Comment by KevinvdBosch** [comment]
Misschien een mogelijkheid om de sbi codes in json formaat te zetten en ze zo in te kunnen laden, zodat ze eventueel later aan te passen zijn mocht er wat veranderen of als je minder codes en categorieën weer wilt geven
