### ISSUE TITLE
Mogelijkheid voor cyclorama implementeren

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Bedrijvenatlas-RH#34]

**Comment by KevinvdBosch** [comment]
De opnames zijn opgenomen door CycloMedia. Hier is een licentie voor nodig om de beelden te gebruiken.
https://www.cyclomedia.com/nl/software-en-diensten

**Comment by HermanAssink** [comment]
@KevinvdBosch: Ik denk dat Joop Voortman de opnamelocaties als WMS-laag beschikbaar kan maken. Door op zo'n punt te klikken springt de gebruiker naar de Cyclorama opname. Rijssen-Holten zal over de benodigde licentie beschikken. Joop Voortman moet je hier verder mee kunnen helpen.

**Comment by HermanAssink** [comment]
Realisatie van deze functie is nu juridisch niet mogelijk omdat kentekens en gezichten niet zijn geblurred op de foto's.
