### ISSUE TITLE
Apart legenda venster met symbolen van lagen die aan staan

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/Bedrijvenatlas-RH#75]
Werkzaamheden:
- Van de wms-lagen kijken welke er aan staan en vanuit de configuratie de kleuren/symbolen en teksten inladen.
- Kleuren/symbolen maken voor de wms lagen en deze in de configuratie zetten samen met de teksten.
- Van de lagen te koop/huur kijken welke er aan staan en deze in een lijst samen met het symbool zetten.
- Van de bedrijven laag kijken welke sublaag er aan staat en hiervan per SBI categorie het symbool pakken en samen met de omschrijving in een lijst zetten.

**Comment by georsnhtn** [comment]
Zie er goed uit. Legenda zichtbaar bij selectie laag en klapt weg bij deselectie. Mooi werk!
