### ISSUE TITLE
Zoekbalk voor het zoeken op SBI code maken

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Bedrijvenatlas-RH#82]

**Comment by georsnhtn** [comment]
Kevin, Heb je deze zoekbalk als actief? Ik zie de status "Ready for review'.

**Comment by KevinvdBosch** [comment]
Ja deze is actief. Deze functionaliteit is in de bestaande zoekbalk geïmplementeerd waardoor het ook mogelijk is op meerdere woorden tegelijk te zoeken

**Comment by georsnhtn** [comment]
Ik heb gezien dat je de brancheomschrijving hebt gekoppeld aan de bedrijfsnaam. Zou je een | teken tussen de bedrijfsnaam en branche omschrijving willen plaatsen? Dan is het overzichtelijker. Kan er ook een ... worden toegevoegd achter in de regel in het resultaatvenster? Waarbij je met een muisbeweging over de tekst de volledige tekst te zien krijgt?
