### ISSUE TITLE
Doorlinken naar Vletgaarsmaten/Elsmoat dmv een URL uit de laag

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Bedrijvenatlas-RH#84]

**Comment by georsnhtn** [comment]
Service bedrijventerreinen_uitgiftelocaties_service als WMS en WFS aangemaakt.

**Comment by georsnhtn** [comment]
In de attribuutset is een link naar de webpaginas met meer info opgenomen.

**Comment by georsnhtn** [comment]
1. Bij inzoomen naar Rijssen moet zowel het bedrijventerrein De Mors, Plaagslagen als Elsmoat te zien zijn. Want aan de Molendijk Noord zijn ook kavels in de verkoop.
2. In het popupvenster kan de info "Kavel info", "Oppervlake", enzovoort worden verwijderd.
3. De doorlinking bij "MEER INFO" opent bij mij geen nieuwe webpagina.

**Comment by KevinvdBosch** [comment]
@georsnhtn 
1. Bedoel je hierbij dat als je via de wizard gaat dat de viewer standaard ingezoomd staat op alleen Elsmoat en moet hiervan de view worden aangepast?
2. Klopt, dit heb ik extern in een settings bestand staan welke niet mee is gekomen. Deze zal ik alsnog uploaden.
3. Zie punt 2.
