### ISSUE TITLE
Bij uitklapscherm bedrijven de volgende tekst in de legenda en symbool aanpassen

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Bedrijvenatlas-RH#85]

**Comment by KevinvdBosch** [comment]
C	Industrie
	D	Productie en distributie van en handel in elektriciteit,
aardgas, stoom en gekoelde lucht
	E	Winning en distributie van water; afval- en afvalwaterbeheer en
sanering
	F	Bouwnijverheid
	G	Groot- en detailhandel; reparatie van auto’s
	H	Vervoer en opslag
	I	Logies-, maaltijd- en drankverstrekking
	J	Informatie en communicatie
	K	Financiële instellingen
	L	Verhuur van en handel in onroerend goed
	M	Advisering, onderzoek en overige specialistische zakelijke
dienstverlening
	N	Verhuur van roerende goederen en overige zakelijke
dienstverlening
	P	Onderwijs
	Q	Gezondheids- en welzijnszorg
	S	Overige dienstverlening

**Comment by KevinvdBosch** [comment]
Moeten de teksten in het menu voor de categorieën worden aangepast naar bovenstaande of volstaat wat er momenteel in staat?

**Comment by HermanAssink** [comment]
@georsnhtn Joop, ons advies is om de teksten niet te lang te maken om het menu leesbaar te houden.
