### ISSUE TITLE
Encoding van aangeleverde data

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Bedrijvenatlas-RH#86]
Zorgen dat diakrieten juist in de viewer worden weergegeven

**Comment by KevinvdBosch** [comment]
Voor zover ik kan zien zijn de encoding problemen bij de kvk bedrijven afkomstig uit de geleverde data. In de laag zoals deze in geoserver staat wordt een ? weergegeven. Ook bij het openen van de shapefile in QGIS wordt een ? bij diakrieten weergegeven.

**Comment by HermanAssink** [comment]
@georsnhtn: Joop, volgens zit het encoding probleem al in de Shapefile die is ge-upload. Kun jij dat verbeteren?

**Comment by KevinvdBosch** [comment]
@georsnhtn : Joop, tijdens het doorklikken van de bedrijvenatlas zag ik dat er een probleem is met de diakrieten. In de geüploade shapefile in GeoDropIn zit dit probleem ook. Zou jij dit in de shapefile aan kunnen passen?
