### ISSUE TITLE
Funda script automatiseren

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/Bedrijvenatlas-RH#88]
Cron script maken, zodat de scripts om funda uit te lezen automatisch starten op een gezette tijd

**Comment by georsnhtn** [comment]
Kevin, start deze script iedere dag?

**Comment by KevinvdBosch** [comment]
Dit script loopt 1x per dag op maandag t/m vrijdag op een willekeurig tijdstip tussen 8 en 16 uur.
